
import { Template } from './template'
import { promptsData } from './promptsData'

// 根据模板 ID 获取 prompt
export function getTemplatePrompt(templateId: string): string {
  return promptsData[templateId] || '';
}

// 从 pp/p.md 解析出的所有模板配置
export const templates: Template[] = [
  {
    id: 'house-plan-3d',
    title: '平面图3D渲染',
    titleEn: '2D Floor Plan to 3D Rendering',
    description: '',
    inImg: '/templates/house_plan.png',
    outImg: '/templates/house_plan_out_pro.png',
    model: 'pro',
    category: '3D渲染',
    requiresVip: false,
  },
  {
    id: 'character-design',
    title: '角色设计',
    titleEn: 'Character Design',
    description: '',
    inImg: null,
    outImg: '/templates/chracter_design_flash.png',
    model: 'flash',
    category: '角色设计',
    requiresVip: false,
  },
  {
    id: 'science-comic',
    title: '科普漫画',
    titleEn: 'Educational Comic',
    description: '',
    inImg: null,
    outImg: '/templates/science_general_pro.png',
    model: 'pro',
    category: '漫画创作',
    requiresVip: false,
  },
  {
    id: 'product-photography',
    title: '商品摄影',
    titleEn: 'Product Photography',
    description: '',
    inImg: null,
    outImg: '/templates/seal_camera_pro.png',
    model: 'pro',
    category: '商品摄影',
    requiresVip: false,
  },
  {
    id: 'sketch-to-image',
    title: '草图生图',
    titleEn: 'Sketch to Image',
    description: '',
    inImg: '/templates/sketch.png',
    outImg: '/templates/sketch_flash.png',
    model: 'flash',
    category: '图像处理',
    requiresVip: false,
  },
  {
    id: 'colorize-sketch',
    title: '草图细化/上色',
    titleEn: 'Sketch Refinement & Coloring',
    description: '',
    inImg: '/templates/cartoon_colorful.jpg',
    outImg: '/templates/cartoon_colorful_pro.png',
    model: 'pro',
    category: '图像处理',
    requiresVip: false,
  },
  {
    id: 'photo-restoration',
    title: '高清修复照片',
    titleEn: 'Photo Restoration & Upscaling',
    description: '',
    inImg: '/templates/old_photo.jpg',
    outImg: '/templates/old_photo_super_pro.png',
    model: 'pro',
    category: '图像处理',
    requiresVip: false,
  },
  {
    id: 'photo-colorization',
    title: '给黑白照片上色',
    titleEn: 'Colorize B&W Photos',
    description: '',
    inImg: '/templates/old_photo_super_pro.png',
    outImg: '/templates/old_photo_color_pro.png',
    model: 'pro',
    category: '图像处理',
    requiresVip: false,
  },
  {
    id: 'interior-design-1',
    title: '给清水房做装修（日式风）',
    titleEn: 'Interior Design (Japanese Style)',
    description: '',
    inImg: '/templates/house.jpg',
    outImg: '/templates/house_pro.png',
    model: 'pro',
    category: '室内设计',
    requiresVip: false,
  },
  {
    id: 'interior-design-2',
    title: '给清水房做装修（地中海风）',
    titleEn: 'Interior Design (Mediterranean)',
    description: '',
    inImg: '/templates/house.jpg',
    outImg: '/templates/house2_pro.png',
    model: 'pro',
    category: '室内设计',
    requiresVip: false,
  },
  {
    id: 'skill-effects',
    title: '设计技能特效',
    titleEn: 'Game Skill VFX Design',
    description: '',
    inImg: '/templates/effect.png',
    outImg: '/templates/effect_pro.png',
    model: 'pro',
    category: '角色设计',
    requiresVip: false,
  },
  {
    id: 'multi-pose',
    title: '一张图出多动作',
    titleEn: 'Multi-Pose Character Sheet',
    description: '',
    inImg: '/templates/chracter2.png',
    outImg: '/templates/chracter2_pro.png',
    model: 'pro',
    category: '角色设计',
    requiresVip: false,
  },
  {
    id: 'food-photography',
    title: '让随手拍变专业摄影',
    titleEn: 'Professional Food Photography',
    description: '',
    inImg: '/templates/food.png',
    outImg: '/templates/food_pro.png',
    model: 'pro',
    category: '商品摄影',
    requiresVip: false,
  },
  {
    id: 'chinese-calligraphy',
    title: '中国古风书法场景',
    titleEn: 'Chinese Calligraphy Scene',
    description: '',
    inImg: null,
    outImg: '/templates/poem_china_old_pro.png',
    model: 'pro',
    category: '人像摄影',
    requiresVip: false,
  },
  {
    id: 'portrait-grid',
    title: '人像摄影网格',
    titleEn: 'Portrait Photography Grid',
    description: '',
    inImg: null,
    outImg: '/templates/person_camera_pro.png',
    model: 'pro',
    category: '人像摄影',
    requiresVip: false,
  },
  {
    id: 'new-calendar',
    title: '新式日历',
    titleEn: 'Creative Calendar Design',
    description: '',
    inImg: null,
    outImg: '/templates/new_cleander.png',
    model: 'pro',
    category: '创意设计',
    requiresVip: false,
  },
  {
    id: 'creative-avatar',
    title: '创意头像',
    titleEn: 'Creative Avatar Design',
    description: '',
    inImg: null,
    outImg: '/templates/creation_head.png',
    model: 'pro',
    category: '创意设计',
    requiresVip: false,
  },
  {
    id: 'food-layer-deconstruction',
    title: '配料合成食材',
    titleEn: 'Food Ingredient Deconstruction',
    description: '',
    inImg: null,
    outImg: '/templates/food_split_merge.png',
    model: 'pro',
    category: '商品摄影',
    requiresVip: false,
  },
  {
    id: 'bilingual-kids-education',
    title: '双语启蒙插图',
    titleEn: 'Bilingual Kids Education',
    description: '',
    inImg: null,
    outImg: '/templates/child_education.png',
    model: 'pro',
    category: '教育图表',
    requiresVip: false,
  },
  {
    id: 'ancient-poetry-illustration',
    title: '古诗生图',
    titleEn: 'Ancient Poetry Illustration',
    description: '',
    inImg: null,
    outImg: '/templates/china_poem.png',
    model: 'pro',
    category: '创意设计',
    requiresVip: false,
  },
  {
    id: 'text-to-manga',
    title: '文生漫画',
    titleEn: 'Text to Manga',
    description: '',
    inImg: null,
    outImg: '/templates/manhua.png',
    model: 'pro',
    category: '漫画创作',
    requiresVip: false,
  },
  {
    id: 'isometric-miniature-1',
    title: '45°等距微缩图(梦幻城堡)',
    titleEn: 'Isometric Miniature (Castle)',
    description: '',
    inImg: null,
    outImg: '/templates/45c.png',
    model: 'pro',
    category: '3D渲染',
    requiresVip: false,
  },
  {
    id: 'isometric-miniature-2',
    title: '45°等距微缩图(同福客栈)',
    titleEn: 'Isometric Miniature (Inn)',
    description: '',
    inImg: null,
    outImg: '/templates/45c2.png',
    model: 'pro',
    category: '3D渲染',
    requiresVip: false,
  },
  {
    id: 'creative-letter',
    title: '创意字母',
    titleEn: 'Creative Letter Design',
    description: '',
    inImg: null,
    outImg: '/templates/word_edu.png',
    model: 'pro',
    category: '教育图表',
    requiresVip: false,
  },
  {
    id: 'hand-drawn-infographic',
    title: '手绘风信息图',
    titleEn: 'Hand-Drawn Infographic',
    description: '',
    inImg: null,
    outImg: '/templates/hand_draw_info.png',
    model: 'pro',
    category: '教育图表',
    requiresVip: false,
  },
  {
    id: 'explosive-product',
    title: '爆炸产品',
    titleEn: 'Explosive Product Showcase',
    description: '',
    inImg: null,
    outImg: '/templates/boom_food.png',
    model: 'pro',
    category: '商品摄影',
    requiresVip: false,
  },
  {
    id: 'artistic-poster',
    title: '海报',
    titleEn: 'Artistic Poster Design',
    description: '',
    inImg: null,
    outImg: '/templates/haibao1.png',
    model: 'pro',
    category: '创意设计',
    requiresVip: false,
  },
  {
    id: 'chinese-new-style-illustration',
    title: '新式国风插画',
    titleEn: 'New Chinese Style Illustration',
    description: '',
    inImg: null,
    outImg: '/templates/china_newstyle_chahua.png',
    model: 'pro',
    category: '创意设计',
    requiresVip: false,
  },
  {
    id: 'emoji-grid-16',
    title: '16宫格表情包',
    titleEn: '16-Grid Emoji Pack',
    description: '',
    inImg: '/templates/duola.png',
    outImg: '/templates/16_grid.png',
    model: 'pro',
    category: '创意设计',
    requiresVip: false,
  },
  {
    id: 'product-refine',
    title: '精修产品',
    titleEn: 'Product Refinement',
    description: '',
    inImg: null,
    outImg: '/templates/ps_tie.png',
    model: 'pro',
    category: '图像处理',
    requiresVip: false,
  },
  {
    id: 'closeup-dramatic-lighting',
    title: '特写打光',
    titleEn: 'Closeup Dramatic Lighting',
    description: '',
    inImg: null,
    outImg: '/templates/texie_daguang.png',
    model: 'pro',
    category: '人像摄影',
    requiresVip: false,
  },
  {
    id: 'daily-realistic-portrait',
    title: '日常写实',
    titleEn: 'Everyday Realism',
    description: '',
    inImg: null,
    outImg: '/templates/real_life.png',
    model: 'pro',
    category: '人像摄影',
    requiresVip: false,
  },
  {
    id: 'vintage-blur-effect',
    title: '虚化复古效果',
    titleEn: 'Vintage Blur Effect',
    description: '',
    inImg: null,
    outImg: '/templates/xuhua_old.png',
    model: 'pro',
    category: '人像摄影',
    requiresVip: false,
  },
]

// 按分类获取模板
export function getTemplatesByCategory(category: string) {
  return templates.filter((t) => t.category === category)
}

// 获取所有分类
export function getAllCategories() {
  return Array.from(new Set(templates.map((t) => t.category))).sort()
}
